name: basic-checks
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python version
        run: python3 --version || true
      - name: List tree
        run: ls -R
